### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by josheewa**

### CODE REVIEW

**Comment by Legend-of-iPhoenix** [comment]
We are not going to rely on an external hosting site for our favicon. You can upload the file to the branch on your repo and link it from there.

**Comment by josheewa** [comment]
My fork or branch? (this branch?) @Legend-of-iPhoenix

**Comment by Legend-of-iPhoenix** [comment]
Your fork.

**Comment by josheewa** [comment]
I know

**Comment by Legend-of-iPhoenix** [comment]
Nothing's coming of this, it seems, and the repo was deleted.

**Comment by josheewa** [comment]
Even in my fork, the favicon wouldn't show up. @Legend-of-iPhoenix

**Pull request closed without merging**
