### PR TITLE
Will that work?

### PR DESCRIPTION
**Pull request by josheewa**
I don't think it'll work, but... it'd be cool.

### CODE REVIEW

**Comment by Legend-of-iPhoenix** [comment]
You'd need to apply the #rainbow class to some elements. It affects the CSS color property, not the background-color.

**Comment by josheewa** [comment]
Alright!

**Comment by Legend-of-iPhoenix** [comment]
It's the .rainbow class. My mind is morning mush.

So just class="rainbow"

**Comment by josheewa** [comment]
:smile:

**Comment by josheewa** [comment]
So I head it like
.rainbow {
something
}? I'm confused @Legend-of-iPhoenix

**Comment by ticalc-travis** [comment]
It has to be done in the HTML. So, for instance, if you have:

    <p>I want rainbow text!</p>

You'd make it:

    <p class="rainbow">I want rainbow text!</p>

And then the next step, I assume, would be to hook up the JS and activate it however it's meant to be.

**Comment by Legend-of-iPhoenix** [comment]
The JS activated by itself.

**Comment by josheewa** [comment]
@Legend-of-iPhoenix What do you mean?

**Pull request closed without merging**
